# Generated by Django 5.0.6 on 2024-06-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_options_alter_users_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='users',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
