# Generated by Django 5.0.6 on 2024-06-22 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_users_managers_users_groups_users_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Activo'), (2, 'De baja'), (3, 'Enfermo'), (4, 'Vacaciones')], default=1),
        ),
    ]
