# Generated by Django 5.0.6 on 2024-06-22 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_users_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='status',
        ),
    ]
