services:
  postgres:
    container_name: postgres_laureate
    image: postgres:latest
    environment:
      POSTGRES_USER: usr_laureate
      POSTGRES_DB: db_laureate
      POSTGRES_PASSWORD: sasa
      PGDATA: /data/postgres
    volumes:
       - postgres-db:/data/postgres
    ports:
      - "5434:5432"


volumes:
  postgres-db:
    driver: local

