# Generated by Django 5.0.6 on 2024-06-20 01:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiarios',
            fields=[
                ('nombre', models.CharField(max_length=32)),
                ('a_paterno', models.CharField(max_length=32)),
                ('a_materno', models.CharField(blank=True, max_length=32, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleados')),
                ('parentesco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.parentesco')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
